.pre-commit-config.yaml, maps.py
=> remove  no longer needed dependencies and functions

eomaps/__init__.py, eomaps/callbacks.py, eomaps/eomaps.py, setup.py, tests/test_basic_functions.py
- `add_marker()` function added to manually add markers
- `add_annotations()` function added to manually add annotations
- annotate can now be used on multiple buttons
- add `text` argument to `m.cb.annotate` to manually specify the text
- add `m.cb.clear_annotations()` function to delete annotations
fix permanent annotations
some minor fixes + more unittests
=> merge for v0.1.2

README.md, eomaps/eomaps.py
fix geo-dataframe not reprojected
allow positional arguments in `savefig`
=> update readme & fix geo-dataframe reprojection

eomaps/__init__.py, eomaps/callbacks.py, eomaps/eomaps.py, setup.py, tests/test_basic_functions.py
- `trimesh_rectangles` has been added as a possible plot-shape (e.g. `m.set_plot_specs(shape="trimesh_rectangles")`
(it uses a triangular mesh for plotting which is useful for contour-plots since pixel-boundaries are invisible)
- option to copy the data with `m.copy(copy_data=True)` has been added
- copy now performs a deep-copy of all properties 
- make `geopandas` an optional import (basic functions do not require geopandas)
- add `pyepsg` as dependency
- use `xcoord` and `ycoord` as labels for annotations
- cleanup callbacks if figure is closed
=> merge for v0.1.3

eomaps/_containers.py, eomaps/_shapes.py, eomaps/callbacks.py, eomaps/eomaps.py, setup.py, tests/test_basic_functions.py
- a new method `m.indicate_masked_points()` is added to indicate points that have been masked
- fix repr-string of the callback-container
- fix adding markers if "geod_circles" have been plotted
- avoid transforming "out-of-bounds" for rectangles 
- don't create markers with radius="pixel" if the shape does not set a radius
=> Merge for v1.0.1

eomaps/_shapes.py, eomaps/callbacks.py
- `m.set_shape.rectangles(radius, radius_crs, n)` now supports calculating intermediate points on the edges
to draw "curved" projected rectangels
- allow setting `n` also in the mark-callback
=> merge for v1.0.2

setup.py
- fix module description on pypi
=> merge for v2.0.1

.gitignore, README.md, docs/EOmaps_examples.rst, docs/usage.rst, eomaps/_cb_container.py, eomaps/_containers.py, eomaps/_webmap.py, setup.py
- There's a new example on how to use WebMap services in the doc!
- make sure WebMap services are put on the assigned default layer
- avoid initializing axes on S1GBM wms-collection initialization
- make sure to update S1GBM layer if "home" or "left/right" toolbar buttons are pressed
=> merge for v2.0.2

README.md, docs/EOmaps_examples.rst, docs/general.rst, eomaps/eomaps.py
- remove unnecessary `print()` in `m.add_gdf`
- update docs & readme to include `conda-forge` install
=> update docs & readme

docs/EOmaps_examples.rst, eomaps/_cb_container.py, eomaps/_shapes.py, eomaps/eomaps.py, eomaps/helpers.py, eomaps/scalebar.py, tests/example1.py, tests/example2.py, tests/example3.py, tests/example4.py, tests/example5.py, tests/example6.py, tests/example7.py, tests/example8.py, tests/example9.py, tests/test_examples.py
- now ALL examples from the doc are run during the unittests
- examples now exist as explicit python files (in tests subfolder)
- the files are directly used as source-code for the tests and the examples in the doc
- fix some warnings, remove obsolete functions and print-statements
=> test examples in unittests

eomaps/_containers.py, eomaps/_webmap.py, eomaps/eomaps.py, tests/test_WMS_capabilities.py, tests/test_basic_functions.py, tests/test_draggable_axes.py
- add a lot of tests
- fix nested copying of Maps objects with "connect=True"
- fix EEA_DiscoMap WMS service
- fix toolbar-action check if no toolbar exists
=> Test examples

eomaps/_shapes.py, eomaps/eomaps.py, eomaps/reader.py, setup.py, tests/test_callbacks.py
... some more quick fixes
- fix rotation angle of ellipses
- remove unnecessary print command
- fix treatment of plot_specs kwargs (vmin, vmax, cmap etc...) in Maps.from_file
- fix defaultargs in add_gdf
=> Merge for V3.1.2

docs/api.rst, eomaps/_containers.py, eomaps/_shapes.py, eomaps/eomaps.py, setup.py
... another bugfix release
- an `AssertionError` is now raised if data- and coordinate dimensions do not match
(to avoid treating datasets with equal size but different shape as valid 1D inputs)
- fix re-projection of data provided with 1D coordinates and 2D data-values (e.g. raster-data)
- fix treatment of nan-values for datashader plots
- update docs for NaturalEarth features and GeoDataFrames
=> Merge for v3.1.3

docs/api.rst, eomaps/_webmap.py, eomaps/callbacks.py, eomaps/eomaps.py, eomaps/helpers.py, eomaps/scalebar.py, eomaps/utilities.py, setup.py, tests/example3.py, tests/example9.py, tests/example_row_col_selector.py
A minor bugfix release (that also brings some miscellaneous convenience functions)
(⭐: new feature, 🍃: new functionality for existing feature)
- ⭐ there's a new function `m.subplots_adjust()` for `Maps` and `MapsGrid` objects to quickly set the margins of the plots as well as the horizontal and vertical spacing between subplots:
```python
m = Maps()
m.subplots_adjust(left=0.2, right=0.8, top=0.9, bottom=0.1)
```
```python
mg = MapsGrid()
mg.subplots_adjust(left=0.2, right=0.8, top=0.9, bottom=0.1, hspace=0.05, wspace=0.15)
```
(these are just shortcuts for `m.figure.gridspec.update()` + `m.redraw()`)
- 🍃 `m.add_colorbar` now has an additional kwarg `log=True/False` to make the y-axis of the histogram logarithmic.
- 🍃 `m.add_scalebar` now provides style-presets via `preset="<preset-name>"` …
=> Merge for v3.3.1

eomaps/_webmap.py, eomaps/callbacks.py, eomaps/eomaps.py, eomaps/helpers.py
[hotfix release to fix issues with multiple maps in one figure]
- fix issues with delayed WebMap services on multiple maps in one figure
- fix issues with `m.all` for multiple maps in one figure
=> [hotfix] for wms-services on multiple maps in one figure

README.md, docs/api.rst, eomaps/_cb_container.py, eomaps/_data_manager.py, eomaps/_webmap.py, eomaps/callbacks.py, eomaps/colorbar.py, eomaps/draw.py, eomaps/eomaps.py, eomaps/helpers.py, eomaps/ne_features.py, eomaps/qtcompanion/widgets/editor.py, eomaps/qtcompanion/widgets/wms.py, eomaps/scalebar.py, tests/example1.py, tests/example2.py, tests/example3.py, tests/example4.py, tests/example5.py, tests/example6.py, tests/example7.py, tests/example8.py, tests/example9.py, tests/example_inset_maps.py, tests/test_basic_functions.py, tests/test_callbacks.py, tests/test_drawer.py
A new major-release that comes with a lot of updates, performance improvements and some very nice new features!
> ❗ There are possibly breaking changes with respect to EOmaps v5.x  ❗ 
> (... and a lot of old syntax from v3.x, v4.x and v5.x has been removed)
> - An overview of the most important changes is provided here: [⚙ From EOmaps v5.x to v6.x](https://eomaps.readthedocs.io/en/dev/FAQ.html#from-eomaps-v5-x-to-v6-x)
EOmaps v6.0 represents a major change in the internals for layer and data management.
🌟 Data is now dynamically pre-selected based on the visible extent prior to plotting, which provides a **huge speed-up** for:
- Zoom/pan on plots of very large datasets
- Initial startup of plots that show only a subset of the assigned datasets
> If you don't need to see the whole extent …
=> Merge for EOmaps v6.0

eomaps/qtcompanion/widgets/wms.py
- fix problems with fetching WMS submenus in the widget if servers are not reachable
=> merge for v6.1

README.md, eomaps/colorbar.py, eomaps/compass.py, eomaps/eomaps.py, eomaps/grid.py, eomaps/helpers.py, eomaps/qtcompanion/app.py, eomaps/qtcompanion/widgets/save.py, tests/example_inset_maps.py
Update export routines to support arbitrary export filetypes
- add new option "rasterize_data" to savefig to control if datasets are rasterized on vector export or not
- update companion-widget
- use export parameters set in the companion-widget as clipboard kwargs
=> Vector graphics export

docs/contribute_env.yml, eomaps/eomaps.py, eomaps/qtcompanion/app.py, eomaps/qtcompanion/base.py, eomaps/qtcompanion/signal_container.py, eomaps/qtcompanion/widgets/annotate.py, eomaps/qtcompanion/widgets/click_callbacks.py, eomaps/qtcompanion/widgets/draw.py, eomaps/qtcompanion/widgets/editor.py, eomaps/qtcompanion/widgets/extent.py, eomaps/qtcompanion/widgets/files.py, eomaps/qtcompanion/widgets/layer.py, eomaps/qtcompanion/widgets/peek.py, eomaps/qtcompanion/widgets/save.py, eomaps/qtcompanion/widgets/utils.py, eomaps/qtcompanion/widgets/wms.py, setup.py, tests/test_env.yml
- use [qtpy](https://github.com/spyder-ide/qtpy) to support multiple Qt versions
- make widget compatible with both Qt5 and Qt6
=> support multiple Qt versions

CONTRIBUTING.md, docs/contribute.rst, environment.yml
Here is a draft of some improvements to the contributing guide for you to run with. Would you please update this to your liking and make sure it has clear instructions for local development and testing?
For https://github.com/pyOpenSci/software-submission/issues/138
=> Improvements to contributing guide

eomaps/_blit_manager.py, eomaps/_maps_base.py, eomaps/eomaps.py, eomaps/layout_editor.py
Refactor Maps class to Maps and MapsBase
=> Refactoring of Maps class

pyproject.toml
Quick-fix to remove obsolete dependencies
=> Updates for v8.3.1
